language: python

python:
- '3.5'

install:
- pip install -r requirements.txt

script:
- python process.py tests/tmp.csv --json_dir /tmp
- cat /tmp/201*.json | jq .[0].location | grep DE
- cat /tmp/201*.json | jq .[0]._reqtime | grep -e '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
- cat /tmp/201*.json | jq .[0].results.responding | grep true
- cat /tmp/201*.json | jq .[0].results.galaxy | grep true
